package enums;

public enum GeneroFotografico {
	RETRATO,
    PAISAJE,
    FOTOGRAFIA_CALLEJERA,
    FOTOGRAFIA_DE_NATURALEZA,
    FOTOGRAFIA_DE_ARQUITECTURA,
    FOTOGRAFIA_DE_MODA,
    FOTOGRAFIA_DOCUMENTAL,
    FOTOGRAFIA_DE_VIAJES,
    FOTOGRAFIA_DE_DEPORTES
}
