package enums;

public enum ProcesoImpresion {
	OFFSET,
    SERIGRAFIA,
    IMPRESION_DIGITAL,
    HUECOGRABADO,
    LITOGRAFIA,
    IMPRESION_FLEXOGRAFICA,
    IMPRESION_POR_SUBLIMACION,
    IMPRESION_TIPOGRAFICA,
    IMPRESION_3D
}
